name: efood_table_booking
description: A new Flutter application.
publish_to: "none" #
version: 1.0.2+4

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  get: ^4.6.5
  intl: ^0.18.1
  shared_preferences: ^2.0.15
  connectivity_plus: ^4.0.2
  firebase_core: ^2.2.0
  firebase_messaging: ^14.1.0
  flutter_local_notifications: ^15.1.0+1
  path_provider: ^2.0.11
  url_strategy: ^0.2.0
  image_picker: ^1.0.2
  cached_network_image: ^3.2.3
  lottie: ^2.0.0
  flutter_custom_clippers: ^2.0.0
  youtube_player_flutter: ^8.1.0
  carousel_slider: ^4.1.1
  shimmer: ^3.0.0
  fluttertoast: ^8.0.9
  getwidget: ^3.0.1
  expandable_text: ^2.3.0
  http: ^1.1.0
  photo_view: ^0.14.0
  esc_pos_utils: ^1.1.0
  print_bluetooth_thermal: ^1.0.9
  gap:

  time_picker_spinner_pop_up: ^1.2.1
  flutter_launcher_icons: ^0.11.0
  hive: ^2.2.3
  hive_flutter:
  hive_generator: ^2.0.1
  simple_speed_dial: ^0.1.7
  number_text_input_formatter: ^1.0.0+7
  logger: ^2.0.2+1

dev_dependencies:
  flutter_lints: ^2.0.1
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter
  build_runner:

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900
